#!/bin/bash

function usage {
  cat <<EOF
deploy 1: deploys code from Github to Heroku apps

Usage: hk deploy branch

Example:

    hk deploy
    hk deploy my-branch
EOF
}

if [ "$HKPLUGINMODE" = info ]; then
  usage
  exit 0
fi

if [ ! -e "$HOME/.heroku/github" ]; then
  echo "No Github credentials. Log in with 'hk gh-login' first."
  exit 1
fi

BRANCH=${1:-master}

TOKEN=$(cat $HOME/.heroku/github)

HEROKUAPP=${HEROKUAPP:-$(git config --get branch.$BRANCH.heroku)}

if [ -z "$HEROKUAPP" ]; then
  echo "Branch $BRANCH is not mapped to any Heroku app. Point it to a Heroku app with"
  echo
  echo "  git config branch.$BRANCH.heroku <heroku-app-name>"
  echo
  echo "or specify a Heroku app with the --app option"
  exit 1
fi

GITHUB_REPO=$(git config --get remote.origin.url | \
              sed -e 's/http:\/\/github.com\///' \
                  -e 's/https:\/\/github.com\///' \
                  -e 's/git@github\.com://' \
                  -e 's/git:\/\/github\.com\///' \
                  -e 's/\.git//' )

VERSION=$(git rev-parse origin/$BRANCH)

echo "Deploying $VERSION on branch $BRANCH in repo $GITHUB_REPO to app $HEROKUAPP"
echo -n "Starting build... "

TAR_URL=$(curl -s -u "$TOKEN:x-oauth-basic" -w "%{redirect_url}" \
          https://api.github.com/repos/$GITHUB_REPO/tarball/$BRANCH)

START_BUILD=$(echo "{\"source_blob\": { \"url\": \"$TAR_URL\", \"version\": \"$VERSION\"}}" | \
              hk api post /apps/$HEROKUAPP/builds)

BUILD_ID=$(echo $START_BUILD | jq -r .id)

echo "done"
echo "Build id: $BUILD_ID"
echo -n "Building"

while true; do 
  echo -n '.'
  sleep 5
  BUILD_OUTPUT=$(hk api get /apps/$HEROKUAPP/builds/$BUILD_ID/result)
  if [ $(echo $BUILD_OUTPUT | jq -r .build.status) != "pending" ]; then
    echo " done"
    echo $BUILD_OUTPUT | jq -r '.lines | map(.line) | reduce .[] as $item (""; . + $item)'
    break
  fi
done


exit 0
