#!/bin/bash

FILES="deploy gh-login show-build"

command -v jq &> /dev/null || {
  echo "Installation failed:"
  echo "jq is required for these plugins to work. Install from http://stedolan.github.io/jq/"
  exit 1
}

HKPATH=${HKPATH:-/usr/local/lib/hk/plugin}

test -e $HKPATH || mkdir -p $HKPATH

test -d $HKPATH || { 
  echo "$HKPATH is not a directory. Cannot install plugins"
  exit 1
}

echo "Installing plugins to $HKPATH:"
for f in $FILES; do
  cp $f $HKPATH/.
  chmod +x $HKPATH/$f
  echo "-------> $f"
done
